spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/bishe?zeroDateTimeBehavior=CONVERT_TO_NULL&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 1
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 3000
    validation-query: SELECT 1 FROM DUAL
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    pool-prepared-statements: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    filters: stat,wall,slf4j
    # 配置web监控,默认配置也和下面相同(除用户名密码，enabled默认false外)，其他可以不配
    web-stat-filter:
      enabled: true
      url-pattern: /*
      exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
      login-username: admin
      login-password: root
      allow: 127.0.0.1
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#不需要重复的创建浪费资源
  pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

